name: tdc-conda-env 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.6.22
  - biopython=1.78
  - dataclasses=0.8
  - fuzzywuzzy=0.18.0
  - huggingface_hub=0.20.3
  - mygene=3.2.2
  - numpy=1.26.4
  - openpyxl=3.0.10
  - python=3.10
  - pip=23.3.1
  - pandas=2.1.4
  - requests=2.31.0
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - pip:
    - accelerate==0.33.0
    - cellxgene-census==1.15.0 
    - datasets<2.20.0
    - dgl==1.1.3
    - evaluate==0.4.2
    - gget==0.28.4
    - moleculeace==3.0.0
    - pydantic==2.6.3
    - gget==0.28.4
    - pydantic==2.6.3
    - gget==0.28.4
    - pydantic==2.6.3
    - pytest==8.3.2
    - rdkit==2023.9.5
    - tiledbsoma==1.11.4
    - torch==2.1.1
    - torch_geometric==2.5.3
    - torchvision==0.16.1
    - transformers==4.43.4
    - yapf==0.40.2

variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"
